from __future__ import annotations

import heapq
import random
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

from .config import ASSETS


SYMBOLS = ASSETS["symbols"]
COIN_VALUE = ASSETS["values"]["coin"]
TRAP_VALUE = ASSETS["values"]["trap"]


@dataclass
class MazeNode:
    """A single maze cell."""

    content: str = SYMBOLS["wall"]
    row: int = 0
    col: int = 0
    extra: Any = None
    params: dict[str, Any] = field(default_factory=dict)

    @property
    def walkable(self) -> bool:
        return self.content != SYMBOLS["wall"]

    def __str__(self) -> str:
        return self.content


class Maze:
    """Rectangular maze generated by Prim's algorithm for Minimum Spanning Tree."""

    def __init__(
        self,
        rows: int,
        cols: Optional[int] = None,
        seed: Optional[int] = None,
        boss_battle: Optional[Callable[["Maze", tuple[int, int]], Any]] = None,
        coin_strategy: Optional[
            Callable[["Maze", list[tuple[int, int]], random.Random], list[tuple[int, int]]]
        ] = None,
        trap_strategy: Optional[
            Callable[["Maze", list[tuple[int, int]], random.Random], list[tuple[int, int]]]
        ] = None,
    ) -> None:
        if cols is None:
            cols = rows
        if rows < 1 or cols < 1:
            raise ValueError("Maze dimensions must be positive")

        self.rows = rows
        self.cols = cols
        self.seed = seed
        self.random = random.Random(seed)
        self.grid: list[list[MazeNode]] = [
            [MazeNode(SYMBOLS["wall"], row, col) for col in range(cols)] for row in range(rows)
        ]
        self.start: Optional[tuple[int, int]] = None
        self.end: Optional[tuple[int, int]] = None
        self.boss: Optional[tuple[int, int]] = None
        self.boss_battle = boss_battle
        self.coin_strategy = coin_strategy
        self.trap_strategy = trap_strategy

    @classmethod
    def generate(
        cls,
        rows: int,
        cols: Optional[int] = None,
        seed: Optional[int] = None,
        boss_battle: Optional[Callable[["Maze", tuple[int, int]], Any]] = None,
        coin_strategy: Optional[
            Callable[["Maze", list[tuple[int, int]], random.Random], list[tuple[int, int]]]
        ] = None,
        trap_strategy: Optional[
            Callable[["Maze", list[tuple[int, int]], random.Random], list[tuple[int, int]]]
        ] = None,
    ) -> "Maze":
        maze = cls(
            rows=rows,
            cols=cols,
            seed=seed,
            boss_battle=boss_battle,
            coin_strategy=coin_strategy,
            trap_strategy=trap_strategy,
        )
        maze._build()
        return maze

    def trigger_boss_battle(self) -> Any:
        if self.boss is None or self.boss_battle is None:
            return None
        return self.boss_battle(self, self.boss)

    def print(self) -> None:
        for row in self.grid:
            print("".join(node.content for node in row))

    def __str__(self) -> str:
        return "\n".join("".join(node.content for node in row) for row in self.grid)

    def _build(self) -> None:
        self._carve_prim_maze()
        self._place_special_cells()

    def _carve_prim_maze(self) -> None:
        """Generate a maze by Prim's minimum spanning tree algorithm."""
        room_rows = list(range(1, self.rows - 1, 2))
        room_cols = list(range(1, self.cols - 1, 2))
        if not room_rows or not room_cols:
            self._carve_fallback_path()
            return

        start_row = room_rows[0]
        start_col = room_cols[0]

        visited: set[tuple[int, int]] = {(start_row, start_col)}
        self._open_cell(start_row, start_col)

        frontier: list[tuple[int, int, int, int, int]] = []
        for nr, nc in self._room_neighbors(start_row, start_col):
            weight = self.random.randint(1, 100)
            heapq.heappush(frontier, (weight, start_row, start_col, nr, nc))

        while frontier:
            _, from_row, from_col, to_row, to_col = heapq.heappop(frontier)
            if (to_row, to_col) in visited:
                continue

            wall_row = (from_row + to_row) // 2
            wall_col = (from_col + to_col) // 2
            self._open_cell(wall_row, wall_col)
            self._open_cell(to_row, to_col)
            visited.add((to_row, to_col))

            for nr, nc in self._room_neighbors(to_row, to_col):
                if (nr, nc) not in visited:
                    weight = self.random.randint(1, 100)
                    heapq.heappush(frontier, (weight, to_row, to_col, nr, nc))

    def _room_neighbors(self, row: int, col: int) -> list[tuple[int, int]]:
        result: list[tuple[int, int]] = []
        for dr, dc in ((-2, 0), (2, 0), (0, -2), (0, 2)):
            next_row = row + dr
            next_col = col + dc
            if 0 < next_row < self.rows - 1 and 0 < next_col < self.cols - 1:
                result.append((next_row, next_col))
        return result

    def _carve_fallback_path(self) -> None:
        for row in range(self.rows):
            if row % 2 == 0:
                for col in range(self.cols):
                    self._open_cell(row, col)
            else:
                for col in range(self.cols - 1, -1, -1):
                    self._open_cell(row, col)
            if row + 1 < self.rows:
                bridge_col = self.cols - 1 if row % 2 == 0 else 0
                self._open_cell(row + 1, bridge_col)

    def _place_special_cells(self) -> None:
        open_cells = self._collect_open_cells()
        if not open_cells:
            return

        if len(open_cells) == 1:
            row, col = open_cells[0]
            self._set_content(row, col, SYMBOLS["start"])
            self.start = (row, col)
            return

        start, end, path = self._find_farthest_pair(open_cells)
        self._set_content(*start, SYMBOLS["start"])
        self._set_content(*end, SYMBOLS["end"])
        self.start = start
        self.end = end

        if len(path) >= 2:
            boss = path[-2]
            if boss not in {start, end}:
                self._set_content(*boss, SYMBOLS["boss"])
                self.boss = boss

        reserved = {start, end}
        if self.boss is not None:
            reserved.add(self.boss)

        remaining = [cell for cell in open_cells if cell not in reserved]
        if not remaining:
            return

        if self.coin_strategy is not None:
            coin_cells = self._apply_strategy(self.coin_strategy, remaining, SYMBOLS["coin"])
            remaining = [cell for cell in remaining if cell not in set(coin_cells)]
        else:
            reserve_traps = self.trap_strategy is None
            remaining = self._place_default_coins(remaining, reserve_traps=reserve_traps)

        if self.trap_strategy is not None and remaining:
            self._apply_strategy(self.trap_strategy, remaining, SYMBOLS["trap"])
        elif remaining:
            self._place_default_traps(remaining)

    def _apply_strategy(
        self,
        strategy: Callable[["Maze", list[tuple[int, int]], random.Random], list[tuple[int, int]]],
        remaining: list[tuple[int, int]],
        marker: str,
    ) -> list[tuple[int, int]]:
        suggested = strategy(self, list(remaining), self.random)
        if not suggested:
            return []
        filtered: list[tuple[int, int]] = []
        remaining_set = set(remaining)
        for cell in suggested:
            if cell in remaining_set and cell not in filtered:
                filtered.append(cell)
        for row, col in filtered:
            self._set_content(row, col, marker)
        return filtered

    def _place_default_coins(
        self, remaining: list[tuple[int, int]], reserve_traps: bool
    ) -> list[tuple[int, int]]:
        min_coins = 1
        min_traps = 1 if reserve_traps else 0
        if self.rows >= 15 and self.cols >= 15:
            min_coins = 5
            min_traps = 3 if reserve_traps else 0

        remaining_count = len(remaining)
        if remaining_count <= 0:
            return remaining

        if remaining_count < min_coins + min_traps:
            if remaining_count >= 2 and reserve_traps:
                min_coins = min(min_coins, remaining_count - 1)
                min_traps = min(min_traps, remaining_count - min_coins)
            else:
                min_coins = min(min_coins, remaining_count)
                min_traps = 0

        max_coin_cap = max(min_coins, remaining_count // 5)
        max_coin_count = max(min_coins, min(remaining_count - min_traps, max_coin_cap))
        coin_count = self.random.randint(min_coins, max_coin_count)

        if coin_count > 0:
            coin_cells = self.random.sample(remaining, coin_count)
            for row, col in coin_cells:
                self._set_content(row, col, SYMBOLS["coin"])
            return [cell for cell in remaining if cell not in set(coin_cells)]
        return remaining

    def _place_default_traps(self, remaining: list[tuple[int, int]]) -> None:
        min_traps = 1
        if self.rows >= 15 and self.cols >= 15:
            min_traps = 3

        remaining_count = len(remaining)
        if remaining_count <= 0:
            return

        trap_min = min(min_traps, remaining_count)
        max_trap_cap = max(min_traps, remaining_count // 8)
        trap_max = min(remaining_count, max_trap_cap)
        trap_count = self.random.randint(trap_min, trap_max)
        if trap_count > 0:
            trap_cells = self.random.sample(remaining, trap_count)
            for row, col in trap_cells:
                self._set_content(row, col, SYMBOLS["trap"])

    def _find_farthest_pair(
        self, open_cells: list[tuple[int, int]]
    ) -> tuple[tuple[int, int], tuple[int, int], list[tuple[int, int]]]:
        start = open_cells[0]
        farthest, _ = self._bfs_farthest(start)
        other, parent = self._bfs_farthest(farthest)
        path = self._reconstruct_path(parent, farthest, other)
        return farthest, other, path

    def _bfs_farthest(
        self, source: tuple[int, int]
    ) -> tuple[tuple[int, int], dict[tuple[int, int], tuple[int, int] | None]]:
        queue: deque[tuple[int, int]] = deque([source])
        parent: dict[tuple[int, int], tuple[int, int] | None] = {source: None}
        farthest = source

        while queue:
            row, col = queue.popleft()
            farthest = (row, col)
            for next_row, next_col in self._neighbors(row, col):
                if (next_row, next_col) not in parent:
                    parent[(next_row, next_col)] = (row, col)
                    queue.append((next_row, next_col))

        return farthest, parent

    def _reconstruct_path(
        self,
        parent: dict[tuple[int, int], tuple[int, int] | None],
        start: tuple[int, int],
        end: tuple[int, int],
    ) -> list[tuple[int, int]]:
        path: list[tuple[int, int]] = [end]
        current = end
        while current != start:
            previous = parent[current]
            if previous is None:
                break
            path.append(previous)
            current = previous
        path.reverse()
        return path

    def _neighbors(self, row: int, col: int) -> list[tuple[int, int]]:
        result: list[tuple[int, int]] = []
        for next_row, next_col in (
            (row - 1, col),
            (row + 1, col),
            (row, col - 1),
            (row, col + 1),
        ):
            if 0 <= next_row < self.rows and 0 <= next_col < self.cols:
                if self.grid[next_row][next_col].walkable:
                    result.append((next_row, next_col))
        return result

    def _collect_open_cells(self) -> list[tuple[int, int]]:
        cells: list[tuple[int, int]] = []
        for row in range(self.rows):
            for col in range(self.cols):
                if self.grid[row][col].walkable:
                    cells.append((row, col))
        return cells

    def _set_content(self, row: int, col: int, content: str) -> None:
        self.grid[row][col].content = content

    def _open_cell(self, row: int, col: int) -> None:
        if 0 <= row < self.rows and 0 <= col < self.cols:
            self.grid[row][col].content = SYMBOLS["floor"]
